#!/bin/bash

cd `dirname $0`
printf "\e[1mCommitting Changes\e[0m\n"
printf "Commit Name: "
read reason

git add .
git commit -m "$reason"
git push https://DocCodes@github.com/DocCodes/doccodes.github.io/ master
