#!/bin/bash

printf "Package Bundle ID: "
read pkg
cd `dirname $0`
mkdir $pkg
cd $pkg
printf "Package Name: "
read name
printf "Package Compatibility: "
read ver
date=`date +"%B %d, %y"`

printf "\e[1mGenerating index.html\e[0m\n"
echo "<div id=\"title\">${name}</div>" > index.html
echo "<div id=\"compat\">${ver}</div>" >> index.html
echo "<div id=\"description\"><p></p></div>" >> index.html
echo "<div id=\"version\">1.0</div>" >> index.html
echo "<div id=\"changelog\"><li>Initial Release</li></div>" >> index.html
echo "<div id=\"update\">${date}</div>" >> index.html
echo "<script type=\"text/javascript\" src=\"../maintemp.js\"></script>" >> index.html

printf "\e[1mGenerating changelog.html\e[0m\n"
echo "<div id=\"title\">Full Changelog</div>" > changelog.html
echo "<div id=\"main\">" >> changelog.html
echo "<ul style=\"list-style: none;\">" >> changelog.html
echo "<li><p><strong>Changes in Version 1.0</strong></p><p></p><ul><li>Initial Release</li></li>" >> changelog.html
echo "</ul" >> changelog.html
echo "</div>" >> changelog.html
echo "<script type=\"text/javascript\" src=\"../subtemp.js\"></script>" >> changelog.html

printf "\e[1mGenerating screenshots.html\e[0m"
echo "<div id=\"title\">Screenshots</div>" > screenshots.html
echo "<div id=\"main\">" >> screenshots.html
echo "</div>" >> screenshots.html
echo "<script type=\"text/javascript\" src=\"../subtemp.js\"></script>" >> screenshots.html
